# Generated by Django 4.0 on 2021-12-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insert',
            new_name='Member',
        ),
    ]
